config/routes.rb
Rails.application.routes.draw do
  root 'sources#index'
  resources :sources, only: [:show] do
  	resources :home_works, only: [:index]
  	get :all_events
  end
  resources :sessions, only: [:new, :create]
  resources :events, only: [] do
    resources :home_works, except: [:index]
  end
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id          :integer          not null, primary key
#  title       :string
#  starts_at   :datetime
#  ends_at     :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  description :text
#  room        :string
#  teacher     :string
#  source_id   :integer
#

class Event < ActiveRecord::Base
  belongs_to :source
  has_many :home_works
end

app/models/home_work.rb
# == Schema Information
#
# Table name: home_works
#
#  id          :integer          not null, primary key
#  title       :string
#  event_id    :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  description :text
#  verified    :boolean
#

class HomeWork < ActiveRecord::Base
  belongs_to :event
  validates :title, :description, presence: true

  def verify!
  	self.verified = true
  	save
  end
end

app/models/menu.rb
# == Schema Information
#
# Table name: menus
#
#  id         :integer          not null, primary key
#  menu_date  :date
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Menu < ActiveRecord::Base
end

app/models/source.rb
# == Schema Information
#
# Table name: sources
#
#  id         :integer          not null, primary key
#  title      :string
#  url        :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Source < ActiveRecord::Base
  has_many :events
  has_many :home_works, -> { uniq }, through: :events

  def get_calendar
    require 'icalendar'
    require "open-uri"
    cal_file = URI.parse("https://hyperplanning.iut.u-bordeaux.fr#{url}").read
    Icalendar::Calendar.parse(cal_file)
  end

  def to_param
    "#{id}-#{title.parameterize}"
  end 

  def ordered_events
    events.where("ends_at >= ?", DateTime.now).where.not(title: "").order('starts_at asc')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_works_controller.rb
class HomeWorksController < ApplicationController
  before_action :connect
  before_action :set_event, except: [:index]
  before_action :set_home_work, except: [:index, :create, :new]

  def index
    @source = Source.find(params[:source_id])
    @home_works = @source.home_works
  end

  def show
  end

  def new
  	@home_work = @event.home_works.new
  end

  def edit
  end

  def create
  	@home_work = @event.home_works.create(home_work_params)
  end

  def update
  	@home_work.update(home_work_params)
    redirect_to source_path(@event.source, anchor: @event.id)
  end

  def destroy
  	@home_work.destroy
  end

  private

  def set_home_work
  	@home_work = @event.home_works.find(params[:id])
  end

  def set_event
    @event = Event.find(params[:event_id])
  end

  def connect
  	#redirect_to new_session_path unless session[:admin]
  end

  def home_work_params
  	params.require(:home_work).permit(:title, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		redirect_to(root_path) if session[:admin]
	end

	def create
		session[:admin] = true if params[:password] == ENV['IUT_PASSWORD']
		session[:admin] ? redirect_to(root_path) : redirect_to(new_session_path)
	end
end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController
  before_action :set_source, except: [:index]

  def index
    @sources = Source.all
  end

  def all_events
    @events = @source.ordered_events.where("starts_at > ?", 10.days.from_now)
  end

  def show
    @home_work = HomeWork.new
    @events = @source.ordered_events.limit(100)
  end

  private

  def set_source
    @source = Source.find(params[:id]||params[:source_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_show.html.erb
<% cache event do %>
<div class="wrapper" id="event-<%= event.id %>">
  <div class="matiere">
    <div class="date">De <span class="bold"><%= (event.starts_at + 2.hours).strftime("%Hh%M") %></span> à <span class="bold"><%= (event.ends_at + 2.hours).strftime("%Hh%M") %></span>
    </div>
    <div class="info">
      <p>
        <svg class="icon" viewBox="0 0 24 24">
          <path d="M11,9H13V7H11M12,20C7.59,20 4,16.41 4,12C4,7.59 7.59,4 12,4C16.41,4 20,7.59 20,12C20,16.41 16.41,20 12,20M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M11,17H13V11H11V17Z" />
        </svg>
        <span><%= event.title %></span>
      </p>
      <p>
        <svg class="icon" viewBox="0 0 24 24">
          <path d="M12,11.5A2.5,2.5 0 0,1 9.5,9A2.5,2.5 0 0,1 12,6.5A2.5,2.5 0 0,1 14.5,9A2.5,2.5 0 0,1 12,11.5M12,2A7,7 0 0,0 5,9C5,14.25 12,22 12,22C12,22 19,14.25 19,9A7,7 0 0,0 12,2Z" />
        </svg>
        <%= event.room %>
      </p>
      <p>
        <svg class="icon" viewBox="0 0 24 24">
          <path d="M12,4A4,4 0 0,1 16,8A4,4 0 0,1 12,12A4,4 0 0,1 8,8A4,4 0 0,1 12,4M12,14C16.42,14 20,15.79 20,18V20H4V18C4,15.79 7.58,14 12,14Z" />
        </svg>
        <%= event.teacher %>
      </p>
    </div>
  </div>
</div>
<% end %>

app/views/home_works/_form.html.erb
<% url = @home_work.persisted? ? event_home_work_path(id: @home_work.id) : event_home_works_path(event_id: @event.id) %>
  	<div class="date">
<%= form_for(@home_work, url: url,  html: {class: "form-horizontal", role: "form"}, remote: !@home_work.persisted?) do |f| %>
		Titre du devoir : <%= f.text_field :title %>
    	Description : <%= f.text_area :description %>
    	<button type="submit">Proposer</button>
    </div>
  <% end %>

app/views/home_works/_index.html.erb
<div class="matiere home-work" id="home-work-<%= event.id %>">
    <div class="date">Devoirs
    	<div class="right">
			<button class="toggle-home-work form" data-id="<%= event.id %>">
				<svg style="width:24px;height:24px" viewBox="0 0 24 24">
				    <path d="M19,13H13V19H11V13H5V11H11V5H13V11H19V13Z" />
				</svg>
			</button>
			<button class="toggle-home-work" data-id="<%= event.id %>">
		        <svg style="width:24px;height:24px" viewBox="0 0 24 24">
				    <path  d="M11,4H13V16L18.5,10.5L19.92,11.92L12,19.84L4.08,11.92L5.5,10.5L11,16V4Z" />
				</svg>
	  		</button>
    	</div>
    </div>
	<% event.home_works.each do |homework| %>
	    <div class="info" id="home-work-el-<%= homework.id %>">
          <h4><%= homework.title %></h4>
		  <p><%= homework.description %></p>
		  <%= link_to edit_event_home_work_path(event_id: event.id, id: homework.id) do %>
		  	Modifier
		  <% end %>
		  &nbsp;
		  <%= link_to event_home_work_path(event_id: event.id, id: homework.id), method: :delete, remote: true, :data => {:confirm => 'Tu es sur ?'} do %>
		  	Supprimer
		  <% end %>
		  <br>
	    </div>
	 <% end %>
</div>

app/views/home_works/_new.html.erb
<div class="wrapper new_hw hidden">
  <div class="matiere">
  <button class="close form">X</button>
  <% @event = event %>
  <%= render 'home_works/form' %>
  </div>
</div>

app/views/home_works/create.js.erb
$('#count').html('<%= @event.home_works.count %>');
<% if @home_work.errors.messages.any? %>
	alert('Le travail proposé n\'est pas valide. Vérifiez les champs.');
<% else %>
	setTimeout(function() {
		$('.new_hw').addClass('hidden');
	}, 200);
	setTimeout(function() {
		window.location.href = window.location.href.split('#')[0] + "#<%= @event.id %>";
		location.reload();
	}, 600);
<% end %>

app/views/home_works/destroy.js.erb
window.location.href = window.location.href.split('#')[0] + "#<%= @event.id %>";
location.reload();

app/views/home_works/edit.html.erb
<div class="wrapper">
  <%= link_to "Retourner à cet évènement", source_path(@event.source.id), class: 'back' %>
  <div class="matiere">
  <%= render 'form' %>
  </div>
</div>

app/views/home_works/index.html.erb
<%= render 'layouts/menu_top' %>
<h3>Les devoirs en <%= @source.title %></h3>
<% @home_works.each do |hw| %>
<div class="wrapper">
  <div class="matiere">
    <div class="date">
		<%= hw.event.title %>
    </div>
    <div class="info">
      <p>
        <svg class="icon" viewBox="0 0 24 24">
          <path d="M11,9H13V7H11M12,20C7.59,20 4,16.41 4,12C4,7.59 7.59,4 12,4C16.41,4 20,7.59 20,12C20,16.41 16.41,20 12,20M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2M11,17H13V11H11V17Z" />
        </svg>
        <span><%= hw.title %></span>
      </p>
      <p>
        <svg class="icon" viewBox="0 0 24 24">
		    <path fill="#000000" d="M19,19H5V8H19M16,1V3H8V1H6V3H5C3.89,3 3,3.89 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19V5C21,3.89 20.1,3 19,3H18V1M17,12H12V17H17V12Z" />
		</svg>
        <span><%= l(hw.event.starts_at, format: "%A %d %B %Y") %></span>
      </p>
      <hr>
      <p>
        <%= hw.description %>
      </p>
    </div>
  </div>
</div>
<% end %>

app/views/home_works/new.html.erb
<div class="wrapper">
  <%= link_to "Retourner à cet évènement", source_path(@event.source.id), class: 'back' %>
  <div class="matiere">
  <%= render 'form' %>
  </div>
</div>

app/views/layouts/_menu_top.html.erb
<%= link_to '/', class: 'home' do %>
  <svg class="icon" viewBox="0 0 24 24">
    <path d="M10,20V14H14V20H19V12H22L12,3L2,12H5V20H10Z" />
  </svg>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Emploi du temps</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, minimal-ui">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="grey-translucent">
  <link rel="apple-touch-icon" type="image/png" href="<%= image_path('icon.png');%>">
  <link rel="shortcut icon" href="<%= image_path('icon.png');%>" type="image/x-icon">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.6.0/slick.css"/>
    <%= csrf_meta_tags %>
</head>
<body>
  <script type="text/javascript" src="//cdn.jsdelivr.net/jquery.slick/1.6.0/slick.min.js"></script>
  <%= yield %>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-84825068-1', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>

app/views/sources/_menu.html.erb
<% cache event do %>
  <% if @events[index + 1] != nil and event.starts_at.strftime("%j") != @events[index + 1].starts_at.strftime("%j") %>
    <% unless Menu.where(menu_date: event.starts_at).first.nil? %>
    <div class="menu">
    <a id="show-menu" onclick="$('.content-repas').toggleClass('show');return false;" href="#">
      <div>
        MENU DU RU
      </div>
      <svg class="icon" viewBox="0 0 24 24">
          <path d="M4,11V13H16L10.5,18.5L11.92,19.92L19.84,12L11.92,4.08L10.5,5.5L16,11H4Z"></path>
      </svg>
    </a>
    <%= Menu.where(menu_date: event.starts_at).first.content.html_safe %>
    </div>
    <% end %>
    <p class="source-info">
    <span>
      <svg style="padding-top:10px;width:20px;height:20px" viewBox="0 0 24 24">
          <path fill="#666" d="M19,19H5V8H19M19,3H18V1H16V3H8V1H6V3H5C3.89,3 3,3.9 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19V5A2,2 0 0,0 19,3M16.53,11.06L15.47,10L10.59,14.88L8.47,12.76L7.41,13.82L10.59,17L16.53,11.06Z" />
      </svg>
    </span>
    <%= @source.title %>
    </p>
  <% end %>
<% end %>

app/views/sources/_pluck_events.html.erb
<% @events.each_with_index do |event, index| %>
  <% new_day = event.starts_at.strftime("%j") != @events[index - 1].starts_at.strftime("%j") %>
  <% if new_day %>
    <% if index != 0 %></div><% end %>
    <div class="day">
      <h3>
      <% if event.starts_at.today? %>
        Aujourd'hui
      <% elsif event.starts_at.to_date == Date.tomorrow %>
        Demain
      <% else %>
        <%= l(event.starts_at, format: "%A %d %B %Y") %>
      <% end %>
      </h3>
  <% end %>
    <%= render 'events/show', event: event, cached: true %>
    <%= render 'menu', index: index, event: event, cached: true %>
<% end %>
</div>

app/views/sources/all_events.js.erb
$('.calendar').slick('unslick');
$('#display-all').remove();
$('.calendar').append('<%= escape_javascript(render('pluck_events')) %> ');
$('.calendar').slick({arrows: false, infinite: false});
$('.calendar').slick('slickGoTo', $('#event-<%= @events.first.id %>').parent('.day').index());

app/views/sources/index.html.erb
<div class="container">
	  <header>
	  	Calendrier IUT
	  </header>
		<% @sources.each do |source| %>
		<a class="source" href="<%=source_path(source.to_param)%>">
			<div>
				<%= source.title %>
			</div>
			<svg class="icon" viewBox="0 0 24 24">
		    	<path d="M4,11V13H16L10.5,18.5L11.92,19.92L19.84,12L11.92,4.08L10.5,5.5L16,11H4Z" />
			</svg>
		</a>
		<% end %>
		<footer>
			<a href="https://github.com/Michaelvilleneuve/iut_calendar" target="_blank" title="Github">Voir le code source</a>
		</footer>
</div>

app/views/sources/show.html.erb
<%= render 'layouts/menu_top' %>

<div class="calendar">
  <%= render 'pluck_events' %>
  <div class="day" id="display-all">
    <%= link_to source_all_events_path(source_id: @source.id), remote: true, id: "load_more" do %>
      <span class="text">Afficher le reste</span>
      <div class="loader hidden">
        <svg xmlns="http://www.w3.org/2000/svg" width="80" height="30" viewBox="0 0 120 30" fill="#333">
          <circle cx="15" cy="15" r="9.60271">
              <animate attributeName="r" from="15" to="15" begin="0s" dur="0.8s" values="15;9;15" calcMode="linear" repeatCount="indefinite"/>
              <animate attributeName="fill-opacity" from="1" to="1" begin="0s" dur="0.8s" values="1;.5;1" calcMode="linear" repeatCount="indefinite"/>
          </circle>
          <circle cx="60" cy="15" r="14.3973" fill-opacity="0.3">
              <animate attributeName="r" from="9" to="9" begin="0s" dur="0.8s" values="9;15;9" calcMode="linear" repeatCount="indefinite"/>
              <animate attributeName="fill-opacity" from="0.5" to="0.5" begin="0s" dur="0.8s" values=".5;1;.5" calcMode="linear" repeatCount="indefinite"/>
          </circle>
          <circle cx="105" cy="15" r="9.60271">
              <animate attributeName="r" from="15" to="15" begin="0s" dur="0.8s" values="15;9;15" calcMode="linear" repeatCount="indefinite"/>
              <animate attributeName="fill-opacity" from="1" to="1" begin="0s" dur="0.8s" values="1;.5;1" calcMode="linear" repeatCount="indefinite"/>
          </circle>
        </svg>
      </div>
    <% end %>
  </div>
</div>

<script>
$('.calendar').slick({arrows: false, infinite: false});

var hash = window.location.hash.substr(1);
if(hash !== "") {
  $('.calendar').slick('slickGoTo', $('#event-'+hash).parent('.day').index());
}
$(document).keydown(function(e){
  if (e.keyCode == 39) {
     $('.calendar').slick('slickNext');
  } else if (e.keyCode == 37) {
    $('.calendar').slick('slickPrev');
  }
});
</script>